### ISSUE TITLE
jira/notify stopped working within the last 24 hours

### ISSUE THREAD

**Issue by Kazark** [CircleCI-Public/jira-orb#52]
Suddenly, without changing our configuration, we are getting 424's on our builds. Our configuration:

```yaml
  notification:
    steps:
      # Call master production
      - when:
          condition:
            equal: [master, << pipeline.git.branch >>]
          steps:
            - jira/notify:
                debug: true
                environment: production
                environment_type: production
                job_type: deployment
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>
      # Otherwise call it testing and assume it's in the dev environment
      - when:
          condition:
            not:
              equal: [master, << pipeline.git.branch >>]
          steps:
            - jira/notify:
                debug: true
                environment: dev
                environment_type: testing
                job_type: deployment
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>
      - run: echo 0
```

We were on version 2.0.1 of the Orb, so I upgraded to 2.2.0. This allowed me to turn error ignoring on to stop the bleeding, but it doesn't solve the problem. Here is a sanitized version of the debug output:

```
Debugging Enabled

  #### DEBUG ####
  OIDC Token: *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Webhook URL: ***************************************************************************************************?verbosity=log
Environment: dev
  ###############


  #### DEBUG ####
  GETTING TAG KEYS
  ###############

Issue keys found:
JIRA-6006
Notification type: deployment

  #### DEBUG ####
  PAYLOAD: {
  "deployments": [
    {
      "deploymentSequenceNumber": "19924",
      "updateSequenceNumber": "1748524991",
      "associations": [
        {
          "associationType": "issueIdOrKeys",
          "values": [
            "JIRA-6006"
          ]
        },
        {
          "associationType": "serviceIdOrKeys",
          "values": [
            ""
          ]
        }
      ],
      "displayName": "Deployment #19924 of our-project",
      "url": "https://circleci.com/gh/OurCompany/our-project/131564",
      "description": "Deployment successful",
      "lastUpdated": "2025-05-29T18:23:11.000Z",
      "label": "Release 2025-05-29T18:23:11.000Z::19294",
      "state": "successful",
      "pipeline": {
        "id": "eac5d4a2-4389-f953-2495-aaf332484e46",
        "displayName": "Deployment: our-project::19924",
        "url": "https://app.circleci.com/pipelines/gh/OurCompany/our-project/19924"
      },
      "environment": {
        "id": "dev",
        "displayName": "DISPLAY_NAME",
        "type": "testing"
      },
      "schemaVersion": "1.0"
    }
  ],
  "providerMetadata": {
    "agent": "circleci-orb"
  }
}
  ###############

Posting payload to CircleCI for Jira Forge app

  #### DEBUG ####
  HTTP Status: 424
HTTP Body: {"timestamp":"2025-05-29T18:23:12.113+00:00","path":"<PATH>","status":424,"error":"Failed Dependency","requestId":"1fb3f172-4118815"}
  ###############


Error posting payload to CircleCI for Jira Forge app
  HTTP Status: 424
  Errors:
parse error: Invalid numeric literal at line 1, column 7

Exited with code exit status 4
```

Let me know what other information I can provide to help you track down this issue.

**Comment by news-manishpatel** [comment]
We noticed the same issue on our pipelines.

**Comment by Andrey-Katyushin** [comment]
Same

**Comment by raulneisbla** [comment]
We have the same issue

**Comment by HennaAbbas** [comment]
Hi All, 

We are reviewing this issue. We'll be in touch with an update when we have one. Thanks for your patience. Let us know if you have any follow-up questions.

**Comment by HennaAbbas** [comment]
Thanks for your patience. We’ve pushed an update to the Jira forage app. Let us know if you continue to see issues.

**Comment by kevin--** [comment]
What do we have to do to get this update? We still see this error on the Configure Page. Thanks!
> 
> CircleCI for Jira - Configure
App update required
Your app CircleCI for Jira is no longer working as it uses a deprecated platform feature. Please check if an update for this app is available through Atlassian Administration, or ask the app developer to upgrade the app. If the app is listed on the marketplace, contact the developer using the Support tab.

**Comment by HennaAbbas** [comment]
Hi @kevin-- Thanks for letting us know. We're continuing to investigate this issue. I'll post an update here when I have one. 

In the meantime, can you try updating the Jira issue without the CircleCI Jira App or orb. You can do this by making an API call from within a run step like so : 
 
```
- run:
    name: Update Jira Issue
    command: |
      curl -X PUT \
        -H "Authorization: Basic $(echo -n $JIRA_EMAIL:$JIRA_API_TOKEN | base64)" \
        -H "Content-Type: application/json" \
        -d '{
          "body": "Build #${CIRCLE_BUILD_NUM} completed successfully. View details: ${CIRCLE_BUILD_URL}"
        }' \
        "https://your-domain.atlassian.net/rest/api/3/issue/${JIRA_ISSUE_KEY}/comment"
```
 
Please note that you will need to save the following environment variables: 
JIRA_EMAIL, JIRA_API_TOKEN, JIRA_ISSUE_KEY

**Comment by mayank-equip** [comment]
We are also facing the same issue, Do we have any update on this? Thanks!

**Comment by RationalEgoism** [comment]
Same

**Comment by 87Hz** [comment]
Same here.

**Comment by nathanfishcircleci** [comment]
We are working on resolving the issue. I don't have a timeline yet. Will repost as soon as its resolved or timeline of when it will be resolved.

**Comment by kevin--** [comment]
Just sharing some more info here -- I did these steps to trigger the update:
1. go to JIRA
2. select from the top bar: Apps > Manage Your Apps
3. select the UPDATE button next to the CircleCI for JIRA application

Now we can access the app in JIRA but it does not seem to be working correctly -- all the fields are blank
![Image](https://github.com/user-attachments/assets/dc4e8211-f37b-46ef-a4cd-8f643fa0cb7b)
then after some time we see multiple of these toasts
![Image](https://github.com/user-attachments/assets/08463af1-8a64-4f5c-953a-59a68af38d4e)

On the CircleCI side, the 424 error persists

**Comment by djmarcos88** [comment]
Just to say that we are also experiencing this issue on my project.

Curious to hear if there's any progress on finding a fix.

**Comment by HennaAbbas** [comment]
Hi Folks! Thanks for your patience. We pushed an update to the Atlassian Forge App. Please update to the latest version of the app to resolve the issue.

**Comment by mayank-equip** [comment]
Thank you, we updated the App in Jira, now we are seeing this error - 

`Notification type: build
Posting payload to CircleCI for Jira Forge app

Error posting payload to CircleCI for Jira Forge app
  HTTP Status: 403
  Errors:
Exiting...
`

**Comment by HennaAbbas** [comment]
Hi @mayank-equip -- Can you [open a support ticket](https://support.circleci.com/hc/en-us/requests/new) so we can gather additional info about your setup. Thanks!

**Comment by HennaAbbas** [comment]
HI @mayank-equip -- I was able to recreate this issue. We've pushed another update to the Atlassian Forge App to resolve the issue. Please update the app. Let us know if you run into any other issues.

**Comment by mayank-equip** [comment]
I can confirm, that it has started working, thank you!

**Comment by kevin--** [comment]
success on our side as well in the past hour or so! (we also got the 403 error previously)

**Comment by djmarcos88** [comment]
I can confirm, the deployments board is working for us again as well!

Would be nice to get some insights on what the root cause of the issue was.

**Comment by HennaAbbas** [comment]
Hi folks,

We apologize for the recent issues with our Forge App. We've identified and resolved the root cause.

The issue occurred when we updated our Forge App runtime to Node 22 (following Atlassian's changelog update: https://developer.atlassian.com/platform/forge/changelog/#CHANGE-2197). This update inadvertently introduced a breaking change that caused the app to stop functioning properly.

The Forge App has been fixed and is now working as intended. Thank you for your patience!

**Comment by Kazark** [comment]
Fixed for us, too. Thanks!
